supplycart/ui

- README.md
- demo/src/App.vue
- src/address/components/Address.vue
- src/address/components/billing/Cambodia.vue
- src/address/components/billing/HongKong.vue
- src/address/components/billing/Indonesia.vue
- src/address/components/billing/Malaysia.vue
- src/address/components/billing/Philippines.vue
- src/address/components/billing/Singapore.vue
- src/address/components/billing/Thailand.vue
- src/address/components/billing/Vietnam.vue
- src/address/components/delivery/Cambodia.vue
- src/address/components/delivery/HongKong.vue
- src/address/components/delivery/Indonesia.vue
- src/address/components/delivery/Malaysia.vue
- src/address/components/delivery/Philippines.vue
- src/address/components/delivery/Singapore.vue
- src/address/components/delivery/Thailand.vue
- src/address/components/delivery/Vietnam.vue
- src/address/mixins/address.js
Updated address component to allow the display of specific field.
> St 3986 fix update address component

- src/address/components/billing/Cambodia.vue
- src/address/components/billing/HongKong.vue
- src/address/components/billing/Indonesia.vue
- src/address/components/billing/Malaysia.vue
- src/address/components/billing/Philippines.vue
- src/address/components/billing/Singapore.vue
- src/address/components/billing/Thailand.vue
- src/address/components/billing/Vietnam.vue
- src/address/components/delivery/Cambodia.vue
- src/address/components/delivery/HongKong.vue
- src/address/components/delivery/Indonesia.vue
- src/address/components/delivery/Malaysia.vue
- src/address/components/delivery/Philippines.vue
- src/address/components/delivery/Singapore.vue
- src/address/components/delivery/Thailand.vue
- src/address/components/delivery/Vietnam.vue
Added `recipient_name` and `recipient_phone `for delivery address.
> ST-3986-FIX-Missing-Values

- src/address/components/delivery/Cambodia.vue
- src/address/components/delivery/HongKong.vue
- src/address/components/delivery/Indonesia.vue
- src/address/components/delivery/Malaysia.vue
- src/address/components/delivery/Philippines.vue
- src/address/components/delivery/Singapore.vue
- src/address/components/delivery/Vietnam.vue
Added condition to display pic_phone, recipient_phone and recipient_name for delivery addresses.
> ST-3986-FIX-Added-Condition-for-missing-values

- demo/src/App.vue
- package.json
- src/form/components/BaseInput.vue
- src/form/components/PhoneInput.vue
- src/form/index.js
- src/form/mixins/input.js
Added phone input and and base input
> ST-4453-FEAT added base input and phone input

- package.json
- src/address/components/billing/Singapore.vue
- src/address/components/delivery/Singapore.vue
> St 4025 fix update singapore address

- package.json
- src/address/components/billing/Singapore.vue
- src/address/components/delivery/Cambodia.vue
- src/address/components/delivery/HongKong.vue
- src/address/components/delivery/Indonesia.vue
- src/address/components/delivery/Malaysia.vue
- src/address/components/delivery/Philippines.vue
- src/address/components/delivery/Singapore.vue
- src/address/components/delivery/Thailand.vue
- src/address/components/delivery/Vietnam.vue
Fixed position of the postcode for Singapore Address. Updated delivery address to display lift_access and requires_permit to yes/no.
> St 4025 fix singapore address postcode

- package.json
- src/address/components/delivery/HongKong.vue
- src/address/components/delivery/Indonesia.vue
- src/address/components/delivery/Philippines.vue
- src/address/components/delivery/Thailand.vue
- src/address/components/delivery/Vietnam.vue
Fixed typo for delivery addresses.
> St 4025 fix typo

- package.json
- src/address/components/billing/Cambodia.vue
- src/address/components/billing/HongKong.vue
- src/address/components/billing/Indonesia.vue
- src/address/components/billing/Malaysia.vue
- src/address/components/billing/Philippines.vue
- src/address/components/billing/Thailand.vue
- src/address/components/billing/Vietnam.vue
- src/address/components/delivery/Cambodia.vue
- src/address/components/delivery/HongKong.vue
- src/address/components/delivery/Indonesia.vue
- src/address/components/delivery/Malaysia.vue
- src/address/components/delivery/Philippines.vue
- src/address/components/delivery/Singapore.vue
- src/address/components/delivery/Thailand.vue
- src/address/components/delivery/Vietnam.vue
Fixed conditions to display lift_access and requires_permit. Rearranged address display value.
> St 3986 fix address components

- package.json
- src/navigation/components/PerPageSelect.vue
missed out updating this. thus pagination did not update
> ST-4835-FIX updated version number

- package.json
- src/address/components/Address.vue
- src/address/components/billing/HongKong.vue
- src/address/components/delivery/HongKong.vue
Fix hong kong addresses not appearing because of spaces.
> ST-5246-FIX-Hong-Kong-Addresses

- package.json
- src/currency/components/Currency.vue
> ST-5266-FIX-Currency-Component

- README.md
- demo/src/App.vue
- package.json
- src/form/components/PasswordInput.vue
- src/form/index.js
> ST-3082-FEAt-Add-Password-Input

- package.json
- src/attachment/components/BaseAttachment.vue
Issue : https://supplycart.atlassian.net/browse/ST-5481
> St 5481 fix add attachment same name

- README.md
- demo/src/App.vue
- package.json
- src/attachment/components/ButtonAttachment.vue
> St 5599 feat improve button attachment

- package.json
- src/currency/constants/currencies.js
based on the checks here: https://github.com/supplycart/ui/blob/eb247a85a3158e83861a9345fb12ef9cedb8ff79/src/currency/components/Currency.vue#L21-L26
> ST-6968 fix USA name

- package.json
- src/address/components/Address.vue
used a more generic way to handle countries with more than one whitespace in their name.
> Generic country address

- demo/src/App.vue
- index.js
- package.json
- src/address/components/Address.vue
- src/form/components/DecimalField.vue
- src/form/index.js
> ST-7355 FEAT new component to display decimal

- demo/src/App.vue
- package.json
- src/currency/index.js
update formatCents function to match updated money component
> ST-7393 FEAT update money function

- package.json
somehow master branch doesnt updated with latest previous version. hence today's update version same as previous ->1.12.6
> ST-7638 FEAT update release version

- package.json
- yarn.lock
latest version does not compatible with current MoneyInput with vue2
> ST-7987 FEAT rollback package update

- demo/src/App.vue
- src/currency/components/MoneyInputV2.vue
- src/currency/components/MoneyInputV2Base.vue
- src/currency/components/index.js
- src/currency/constants/currencySettings.js
- src/currency/constants/index.js
> ST-8015 FEAT new version of money input

- src/address/components/BillingAddress.vue
- src/address/components/DeliveryAddress.vue
- src/address/constants/address.js
Add tax registration no
Remove address breaklines
> ST-9217 FEAT Update Address component

- package.json
- src/currency/components/MoneyInputV2Base.vue
Remove the margin here. If wanna use margin, can add in the parent's component
> ST-10986 fix remove money input margin

- demo/package.json
- demo/src/App.vue
- demo/yarn.lock
- package.json
- src/datetime/components/DatePicker.vue
- src/datetime/components/DateTime.vue
- src/datetime/constants/flatpickr.js
- src/datetime/index.js
> Revert "ST-12549 FIX date fns and demo lock modification"

- package.json
- src/form/components/DropdownInput.vue
https://supplycart.atlassian.net/browse/ST-12723
(Jira comment)[https://supplycart.atlassian.net/browse/ST-12723?focusedCommentId=45891]
Remove the validation message if it's not required
> ST-12723 FEAT [UI] incorrect drowdown message if not required
